# Generated by Django 4.0.1 on 2022-01-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlescope_is_main_alter_articlescope_scope_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescope',
            old_name='scope',
            new_name='tag',
        ),
    ]
